### ISSUE TITLE
Broken images / links in the 3.7 frontend web monitor

### ISSUE THREAD

**Issue by bbockelm** [glideinWMS/glideinwms#36] opened 2020-11-23 16:50 UTC
Hi,

Now, it could be a function of the new Docker-based deploy, but it appears a number of the links are broken.  See:

https://glow-fe-osgdev.chtc.wisc.edu/vofrontend/monitor/

Looking at a few, it's possible some relative links are problematic?  Is there a working 3.7.1 FE and web interface we can compare to?

Brian

**Comment by mambelli** [comment] 2020-12-03 17:21
Hi Brian, 
it may be a problem caused by the container. In my tests on Fermicloud and other installations work correctly. See CMS ITB:
http://vocms080.cern.ch/vofrontend/monitor/

Do you have the folder w/ the images, /var/lib/gwms-frontend/web-area/monitor/images/ ?
Is it readable and executable from the web server?
Please let me know what you find out.

Thanks,
Marco

**Comment by mambelli** [comment] 2020-12-04 20:08
@bbockelm Any news on what is causing this in your installation?

**Comment by brianhlin** [comment] 2021-05-12 18:05
@mambelli I believe it's an issue with the Apache config. See a patch here: https://opensciencegrid.atlassian.net/browse/SOFTWARE-4578

**Comment by mambelli** [comment] 2021-05-18 21:41
@brianhlin, @aaronmoate, The patch suggested in the OSG software ticket and in PR#47 is incorrect. 
The image files should be also in `/var/lib/gwms-frontend/web-area/monitor/images` (line 428 and 836 of the spec file, in glideinwms-vofrontend-core RPM), which is within the web space/Alias already defined.
The files are also in web-base to allow the `upgrade` command but should not be served by that directory.
I see that https://vo-frontend-glow.chtc.wisc.edu/vofrontend/monitor/index.html is still not serving the images.
Are the files not in /var/lib/gwms-frontend/web-area/monitor/images?
If no, was glideinwms-vofrontend-core (glideinwms-vofrontend-standalone in older versions) installed?
If yes, are the permissions correct? Is the httpd conf file the one from GWMS?

**Comment by brianhlin** [comment] 2021-05-18 22:19
@mambelli I think this should answer all of your questions. Let me know if you need anything else

```
[root@vo-frontend-glow-68fcdd5d66-dz9j8 /]# ls -l /var/lib/gwms-frontend/w
eb-area/monitor/images                                                                                           
ls: cannot access /var/lib/gwms-frontend/web-area/monitor/images: No such file or directory
[root@vo-frontend-glow-68fcdd5d66-dz9j8 /]# rpm  -q glideinwms-vofrontend-core glideinwms-vofrontend-standalone
glideinwms-vofrontend-core-3.9.1-1.osg35.el7.noarch
glideinwms-vofrontend-standalone-3.9.1-1.osg35.el7.noarch
[root@vo-frontend-glow-68fcdd5d66-dz9j8 /]# ls -l /etc/httpd/
conf/           conf.d/         conf.modules.d/ logs/           modules/        run/            
[root@vo-frontend-glow-68fcdd5d66-dz9j8 /]# ls -l /etc/httpd/conf.d
total 24
-rw-r--r-- 1 root root   31 May 18 21:39 50-server-name.conf
-rw-r--r-- 1 root root 2926 Nov 16  2020 autoindex.conf
-rw-r--r-- 1 root root  421 Feb 11 22:31 gwms-frontend.conf
-rw-r--r-- 1 root root  366 Nov 16  2020 README
-rw-r--r-- 1 root root 1252 Nov 16  2020 userdir.conf
-rw-r--r-- 1 root root  824 Nov 16  2020 welcome.conf
```

**Comment by mambelli** [comment] 2021-05-19 00:17
@brianhlin Something is wrong with your installation. Someone or something deleted those files. Do you think it was some GlideinWMS script? It is the first time I notice it. Could you run the rpm -ql and rpm -V command?
Below you can see that the verification catches the missing files.
```
[root@fermicloud171 ~]# rpm -ql glideinwms-vofrontend-core | grep "monitor/image"
/var/lib/gwms-frontend/web-area/monitor/images
/var/lib/gwms-frontend/web-area/monitor/images/frontendGroupGraphsNow.small.png
/var/lib/gwms-frontend/web-area/monitor/images/frontendRRDBrowse.small.png
/var/lib/gwms-frontend/web-area/monitor/images/frontendRRDGroupMatix.small.png
/var/lib/gwms-frontend/web-area/monitor/images/frontendStatus.small.png
[root@fermicloud171 ~]# ls -al /var/lib/gwms-frontend/web-area/monitor/images/
total 248
drwxr-xr-x. 2 frontend frontend  4096 May 18 19:05 .
drwxr-xr-x. 7 frontend frontend  4096 May 18 19:05 ..
-rw-r--r--. 1 frontend frontend 71796 Feb 11 14:41 frontendGroupGraphsNow.small.png
-rw-r--r--. 1 frontend frontend 55660 Feb 11 14:41 frontendRRDBrowse.small.png
-rw-r--r--. 1 frontend frontend 49041 Feb 11 14:41 frontendRRDGroupMatix.small.png
-rw-r--r--. 1 frontend frontend 49374 Feb 11 14:41 frontendStatus.small.png
[root@fermicloud171 ~]# yum list glideinwms*
Loaded plugins: langpacks, priorities
179 packages excluded due to repository priority protections
Installed Packages
glideinwms-common-tools.noarch                                                                                 3.9.1-1.osg35.el7                                                                         @osg-contrib
glideinwms-condor-common-config.noarch                                                                         3.9.1-1.osg35.el7                                                                         @osg-contrib
glideinwms-glidecondor-tools.noarch                                                                            3.9.1-1.osg35.el7                                                                         @osg-contrib
glideinwms-libs.noarch                                                                                         3.9.1-1.osg35.el7                                                                         @osg-contrib
glideinwms-minimal-condor.noarch                                                                               3.9.1-1.osg35.el7                                                                         @osg-contrib
glideinwms-usercollector.noarch                                                                                3.9.1-1.osg35.el7                                                                         @osg-contrib
glideinwms-userschedd.noarch                                                                                   3.9.1-1.osg35.el7                                                                         @osg-contrib
glideinwms-vofrontend.noarch                                                                                   3.9.1-1.osg35.el7                                                                         @osg-contrib
glideinwms-vofrontend-core.noarch                                                                              3.9.1-1.osg35.el7                                                                         @osg-contrib
glideinwms-vofrontend-httpd.noarch                                                                             3.9.1-1.osg35.el7                                                                         @osg-contrib
glideinwms-vofrontend-standalone.noarch                                                                        3.9.1-1.osg35.el7                                                                         @osg-contrib
Available Packages
glideinwms-factory.noarch                                                                                      3.6.5-1.osg35.el7                                                                         osg
glideinwms-factory-condor.noarch                                                                               3.6.5-1.osg35.el7                                                                         osg
 .....
[root@fermicloud171 ~]# rpm -V glideinwms-vofrontend-core
.....UG..  c /etc/gwms-frontend/frontend.xml
(reverse-i-search)`': rpm -qf ^Car/lib/gwms-frontend/web-area/monitor/images/
[root@fermicloud171 ~]# mv /var/lib/gwms-frontend/web-area/monitor/images ~/ppp
[root@fermicloud171 ~]# rpm -V glideinwms-vofrontend-core
.....UG..  c /etc/gwms-frontend/frontend.xml
missing     /var/lib/gwms-frontend/web-area/monitor/images
missing     /var/lib/gwms-frontend/web-area/monitor/images/frontendGroupGraphsNow.small.png
missing     /var/lib/gwms-frontend/web-area/monitor/images/frontendRRDBrowse.small.png
missing     /var/lib/gwms-frontend/web-area/monitor/images/frontendRRDGroupMatix.small.png
missing     /var/lib/gwms-frontend/web-area/monitor/images/frontendStatus.small.png
```

**Comment by mambelli** [comment] 2021-06-08 04:50
Closing the issue since it is not a problem in GlideinWMS.
I'd be curious to know what caused the problem (missing files)

**Closed by mambelli** 2021-06-08 04:50 UTC
